### ISSUE TITLE
Snapshot creation fails if not all containers are used

### ISSUE THREAD

**Issue by constellates** [poldracklab/bids-core#4]
The BIDS structure has some flexibility regarding the level of directory depth. On the deepest datasets we use acquisition containers as the deepest directory. On shallower dataset acquisitions are not used at all. It appears snapshot creation fails on datasets that don't use acquisitions. Here's the stack trace I'm seeing.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/srv/scitran/api/api.py", line 136, in dispatcher
    rv = router.default_dispatcher(request, response)
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/srv/scitran/api/base.py", line 128, in dispatch
    return super(RequestHandler, self).dispatch()
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/srv/scitran/api/handlers/snapshothandler.py", line 69, in create
    result = permchecker(snapshot.create)('POST', _id=origin_id)
  File "/srv/scitran/api/dao/snapshot.py", line 68, in create
    return _store(hierarchy)
  File "/srv/scitran/api/dao/snapshot.py", line 62, in _store
    config.db.acquisition_snapshots.insert_many(acquisitions)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 665, in insert_many
    raise TypeError("documents must be a non-empty list")
TypeError: documents must be a non-empty list
```

@rentzso let me know if I can provide more info or otherwise help.

**Comment by constellates** [comment]
I forgot to mention. In this case snapshot creation returns a 500 error, but then if I get the list of snapshots a new one was created.

**Comment by constellates** [comment]
Thanks @rentzso. I just tested and this is working.
